# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
    paths: ['./api/**']
  pull_request:
    branches: [ "main" ]
    paths: ['./api/**']
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET    
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      working-directory: ./api
      run: dotnet restore
    - name: Build
      working-directory: ./api
      run: dotnet build --no-restore
    - name: Publish
      working-directory: ./api
      run: dotnet publish
    - name: Deploy to Simply        
      uses: talunzhang/auto-web-deploy@v1.0.1
      with:
          website-name: mattx2642-001-site22
          server-computer-name: https://win8210.site4now.net:8172/msdeploy.axd?site=mattx2642-001-site22
          server-username: mattx2642-001
          server-password: ${{ secrets.SERVER_PASSWORD }}
          source-path: '\bin\Release\net9.0\publish\'
